site_name: SeaTable Admin Manual
site_url: https://admin.seatable.io/
site_author: SeaTable GmbH
site_description: >
  Official SeaTable Admin Manual.

# Repository
repo_name: seatable/seatable-admin-docs
repo_url: https://github.com/seatable/seatable-admin-docs/

# Copyright
copyright: Copyright &copy; 2022 - 2024 SeaTable GmbH

# Configuration
theme:
  name: material
  features:
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.sections # top-level sections are rendered as groups in the sidebar for viewports above 1220px
    - navigation.indexes # documents can be directly attached to sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.annotate # offer a comfortable and friendly way to attach arbitrary content to specific sections of code
  custom_dir: overrides

  # icon & favicon
  logo: media/SeaTable256-256.png
  favicon: media/seatable-favicon.ico

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized
  - redirects:
      redirect_maps:
        #"changelog/server-changelog.md": "https://seatable.io/docs/changelog/"
        "changelog/changelog-for-seatable-professional-server.md": "https://seatable.io/docs/changelog/"

hooks:
  - overrides/hooks/shortcodes.py

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seatable/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/seatable/seatable-enterprise
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/seatable/
  status:
    new: Work in progress
  analytics:
    provider: matomo
    site_id: 3
    provider_url: https://wp-stats.seatable.io/

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      guess_lang: true
  - pymdownx.details # creates collapsible elements that hide their content
  - pymdownx.superfences: # allows 1) nesting of fences 2) custom fences 3) disable indented code
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys # make entering and styling keyboard key presses easier
  - pymdownx.tabbed: # provides a syntax to easily add tabbed Markdown content
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # Hooks


nav:
  - Introduction:
      - index.md
      - Architecture: architecture.md
      - Security: security.md
      - Requirements: requirements.md
      - System Limitations: limitations/system_limitations.md
      - Server Editions: editions.md
      - Get Support: get_support.md
      - EULA: dtable-server-license.md
      #- Other manuals: others.md
      - Changelog: changelog/server-changelog.md

  - Installation:
      - How to start: installation-rework/start.md
      - Our deployment approach: installation-rework/start_details.md
      - Single-Node Installation:
          - SeaTable-Server: installation-rework/basic-setup.md
          - Python Pipeline: installation-rework/components/python-pipeline.md
          - n8n: installation-rework/components/n8n.md
          - Office Editor:
              - Collabora: installation-rework/components/collabora.md
              - OnlyOffice: installation-rework/components/onlyoffice.md
          - Monitoring:
              - Uptime Kuma: installation-rework/components/uptime-kuma.md
              - Zabbix: installation-rework/components/zabbix.md
          - FAQ / Troubleshooting: installation-rework/faq.md

      - Advanced Topics:
          - Webserver:
              - Custom Reverse Proxy: installation-rework/advanced/custom_proxy.md
              - Custom Certificates: installation-rework/advanced/custom_certificates.md
              - Additional Subdomains: installation-rework/advanced/additional_subdomains.md
              - Air Gap Installation: installation-rework/advanced/air_gap_installation.md
          - S3 Object Storage:
              - Configuration: config/enterprise/s3.md
              - Migration: config/enterprise/s3_migration.md
          - Python Pipeline:
              - Custom Python Runner: installation-rework/advanced/python_pipeline_custom_python_runner.md
              - Separate Python Pipeline: installation-rework/advanced/python_pipeline_dedicated_server.md
              - Configure Python Pipeline: installation-rework/advanced/python_pipeline_configuration.md
              - Python Pipeline Workflow: installation-rework/advanced/python_pipeline_workflow.md
          - MariaDB (standalone): installation-rework/advanced/database_standalone.md
          - Seafile (external): installation-rework/components/seafile.md

      - Cluster Setup:
          - SeaTable Cluster: docker/Cluster/seatable_cluster.md
          - dtable-server cluster: docker/Cluster/dtable-server Cluster.md
          - dtable-db (standalone): docker/Cluster/dtable-db Standalone.md
          - dtable-events (standalone): docker/Cluster/dtable-events Background node.md

  - Configuration:
      - config/index.md
      - Features:
          - Plugins: config/plugins.md
          - Logo/Styles: config/custom_css.md
          - Templates and Manual: config/templates_and_manual.md
          - Email Sending: config/sending_email.md
          - Roles and Permissions: config/enterprise/roles_permissions.md
          - Frontend: config/frontend_html_template_system.md
          - Universal Apps: config/universal_apps.md
          - Autostart: config/autostart.md
          - Base Rows Limit: config/base_rows_limit.md
      - User Hierarchy:
          - Overview: config/user_hierarchy/overview.md
          - Groups: config/user_hierarchy/groups.md
          - Teams/Organizations: config/user_hierarchy/teams_organizations.md
          - Departments: config/user_hierarchy/departments.md
      - Authentication:
          - Overview: authentication/overview.md
          - Methods:
              - Two Factor Authentication: authentication/two_factor_auth.md
              - LDAP: authentication/ldap.md
              - OAuth: authentication/oauth.md
              - SAML: authentication/saml.md
              - JWT-Token: authentication/jwt.md
          - Switch authentication: authentication/auth_switch.md
      - Available Configuration Options:
          - Environment variables: config/environment_variables.md
          - Configuration files:
              - ccnet.conf: config/ccnet-conf.md
              - dtable-db.conf: config/dtable_db_conf.md
              - dtable-events.conf: config/dtable-events-conf.md
              - dtable_server_config: config/dtable_server_config.md
              - dtable-storage-server.conf: config/dtable_storage_server_conf.md
              - dtable_web_settings.py: config/dtable_web_settings.md
              - seafile.conf: config/seafile-conf.md
              - seatable-controller.conf: config/seatable-controller-conf.md

  - Upgrade:
      - How to upgrade: upgrade/upgrade_manual.md
      - Extra Upgrade Notices: upgrade/extra-upgrade-notice.md

      - Migrations:
          - Switch SeaTable Edition: docker/Enterprise-Edition/migrate_seatable_editions.md
          - Switch Installation Method (v4.3): upgrade/migrate_seatable_release.md

  - Maintenance:
      - Backup and Recovery: maintain/backup_recovery.md
      - Clean Database: maintain/clean_database.md
      - Clean Storage: maintain/seatable_gc.md
      - Filesystem check: maintain/seatable_fsck.md
      - Change URL: maintain/others.md
      - Command Line Tools: maintain/others.md
      - Advanced Debugging:
          - Custom error messages: maintain/debugging.md
#  - Migration:
#      - Mysql: config/ccnet-conf.md
#      - Postgres: config/ccnet-conf.md
#      - Airtable: config/ccnet-conf.md
